name: Git Drop Commit

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Hash of the commit to drop'
        required: true
      target_branch:
        description: 'Branch to operate on'
        required: true
        default: 'main'

jobs:
  drop-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          persist-credentials: true
          fetch-depth: 100

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Drop Commit
        run: |
          COMMIT_HASH=${{ github.event.inputs.commit_hash }}
          PARENT_HASH=$(git rev-parse $COMMIT_HASH^)
          git rebase --onto $PARENT_HASH $COMMIT_HASH
          
      - name: Push changes
        run: |
          git push origin ${{ github.event.inputs.target_branch }} --force-with-lease
